#!/bin/bash
#
# generate-build-info.sh
# Generates BuildInfo.generated.swift with current git and build information
#
# Usage: ./scripts/generate-build-info.sh
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(dirname "$SCRIPT_DIR")"
OUTPUT_FILE="$PROJECT_ROOT/radial-menu/radial-menu/BuildInfo.generated.swift"

# Get git information
cd "$PROJECT_ROOT"

if git rev-parse --git-dir > /dev/null 2>&1; then
    COMMIT_HASH=$(git rev-parse HEAD 2>/dev/null || echo "unknown")
    BRANCH=$(git rev-parse --abbrev-ref HEAD 2>/dev/null || echo "unknown")

    # Check for uncommitted changes
    if git diff-index --quiet HEAD -- 2>/dev/null; then
        IS_DIRTY="false"
    else
        IS_DIRTY="true"
    fi
else
    COMMIT_HASH="unknown"
    BRANCH="unknown"
    IS_DIRTY="false"
fi

# Get build timestamp in ISO 8601 format
BUILD_TIMESTAMP=$(date -u +"%Y-%m-%dT%H:%M:%SZ")

# Generate the Swift file
cat > "$OUTPUT_FILE" << EOF
//
//  BuildInfo.generated.swift
//  radial-menu
//
//  AUTO-GENERATED FILE - DO NOT EDIT
//  Generated by scripts/generate-build-info.sh
//  Generated at: $BUILD_TIMESTAMP
//

import Foundation

/// Generated build information - do not edit manually
enum GeneratedBuildInfo {
    static let commitHash = "$COMMIT_HASH"
    static let buildTimestamp = "$BUILD_TIMESTAMP"
    static let branch = "$BRANCH"
    static let isDirty = $IS_DIRTY
}
EOF

echo "Generated build info:"
echo "  Commit: ${COMMIT_HASH:0:7}"
echo "  Branch: $BRANCH"
echo "  Dirty: $IS_DIRTY"
echo "  Timestamp: $BUILD_TIMESTAMP"
echo "  Output: $OUTPUT_FILE"
